apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rnacos.fullname" . }}
  labels:
    {{- include "rnacos.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    # 1. 读取当前ip
    export RNACOS_RAFT_NODE_ADDR={{ include "rnacos.fullname" . }}-$(echo $MY_POD_NAME | grep -o '[0-9]\+$').{{ include "rnacos.fullname" . }}-headless:9848
    export RNACOS_RAFT_NODE_ID=$(expr 1 + $(echo $MY_POD_NAME | grep -o '[0-9]\+$'))
    export RNACOS_RAFT_JOIN_ADDR={{ include "rnacos.fullname" . }}-0.{{ include "rnacos.fullname" . }}-headless:9848
    # export RNACOS_RAFT_AUTO_INIT=true
    export RUST_LOG={{ .config.rustLog }}
    export RNACOS_HTTP_WORKERS={{ .config.httpWorkers }}
    export RNACOS_CONSOLE_LOGIN_ONE_HOUR_LIMIT={{ .config.consoleLoginOneHourLimit }}
    echo $RNACOS_RAFT_NODE_ADDR
    echo $RNACOS_RAFT_NODE_ID
    echo $RNACOS_RAFT_JOIN_ADDR
    exec /usr/bin/rnacos
