apiVersion: v1
kind: Service
metadata:
  name: {{ include "rnacos.fullname" . }}
  labels:
    {{- include "rnacos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8848
      targetPort: 8848
      protocol: TCP
      name: http
    - port: 9848
      targetPort: 9848
      protocol: TCP
      name: grpc
  selector:
    {{- include "rnacos.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rnacos.fullname" . }}-headless
  labels:
    {{- include "rnacos.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 8848
      targetPort: 8848
      protocol: TCP
      name: http
    - port: 10848
      targetPort: 10848
      protocol: TCP
      name: admin
    - port: 9848
      targetPort: 9848
      protocol: TCP
      name: grpc
  selector:
    {{- include "rnacos.selectorLabels" . | nindent 4 }}

